### ISSUE TITLE
Where is the content from the uploaded file?

### ISSUE THREAD

**Issue by ogrotten** [coddredd/react-files-hooks#2]
I used and tweaked your example. 

```
import React, { useEffect, useState } from 'react';
import { useUploader } from 'react-files-hooks';

function App() {
	const [file, setFile] = useState({})
	const { uploader, reset } = useUploader({
		onSelectFile: incoming => {
			setFile(incoming)
		},
		onError: error => {
			console.log(`App.js 11: `, error)
		},
		validTypes: ["text/plain"]
		// validTypes: ["application/json", "application/xml"]
	});

	useEffect(() => {
		console.log(file)
	}, [file])

	return (
		<div>
			<input {...uploader} id="input" />
			<button onClick={reset}>Reset</button>
			{console.log(`App.js 24: `, file)}
		</div>
	)

}

export default App;
```
The example file I uploaded using this is a text file `thing.txt` with one line of text `Now is the time and all that.`

The conlogs In the useEffect and the component render return an informational object, but the data is not part of it.

![image](https://user-images.githubusercontent.com/8119012/102811648-4c9ffa80-438b-11eb-9d2a-19813280abf8.png)

How do I get the data from the object that's returned to `incoming` when using `useUploader`?

**Comment by ogrotten** [comment]
After some more digging, I now understand that this module uploads the file, but makes no attempt to provide the data. There's an additional JS api that needs to be used if you want to read data.

[Here is a codesandbox](https://codesandbox.io/s/read-json-file-and-store-in-var-c3s8k?file=/src/Upload.jsx) for uploading and reading a file. 

For anyone else coming around for the same problem, here's my final sample code that reads a json file:

```
import React, { useEffect, useState } from 'react';
import { useUploader } from 'react-files-hooks';

function App() {
	const [file, setFile] = useState({})

	const { uploader, reset } = useUploader({
		onSelectFile: incoming => {
			const fileReader = new FileReader();
			fileReader.readAsText(incoming[0], "UTF-8");
			fileReader.onload = e => {
				setFile(JSON.parse(e.target.result));
			};
		},
		onError: error => {
			console.log(`App.js 11: `, error)
		},
		validTypes: ["application/json"]
	});

	useEffect(() => {
		console.log(file)
	}, [file])

	return (
		<div>
			<input {...uploader} id="input" />
			<button onClick={reset}>Reset</button>
			{console.log(`App.js 24: `, file)}
		</div>
	)

}

export default App;

```

**Comment by coddredd** [comment]
@ogrotten Thanks for your comment. It is a good idea to include this functionality in future updates.

**Comment by ogrotten** [comment]
I don't know if you **_need_** to include it, as it starts to get into the "batteries included" territory. If it were complex I might agree with you. At this point, you could probably include the snippet and the link to the code sandbox in the docs and that would be enough.

So I would say you could add a paragraph to the readme. I'll make a PR!
